on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Toml Sort

jobs:
  toml-sort:
    name: Toml Sort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - run: cargo install --git https://github.com/Moonsong-Labs/toml_sort/
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - run: find . -name Cargo.toml | xargs -L1 toml-sort --check
