# This is a configuration file for zombienet: https://github.com/paritytech/zombienet
# You can use it to launch a custom relay-para network with relative ease.
# After building the collator and relay chain binaries, and installing zombienet 1.3.74 onwards,
# zombienet --provider podman spawn zombienet.toml

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "../polkadot-sdk/target/release/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "relay-01"
  validator = true
  args = ["-lruntime=debug", "-lparachain=debug", "-ltuxedo-core=debug", "-ltuxvb=debug"]

  [[relaychain.nodes]]
  name = "relay-02"
  validator = true
  args = ["-lruntime=debug", "-lparachain=debug", "-ltuxedo-core=debug", "-ltuxvb=debug"]


[[parachains]]
id = 2000

  [[parachains.collators]]
  name = "alice"
  image = "ghcr.io/off-narrative-labs/tuxedo-parachain:latest"
  command = "./target/debug/parachain-template-node"
  args = ["--alice"]

  [[parachains.collators]]
  name = "tuxedo-full-node"
  image = "ghcr.io/off-narrative-labs/tuxedo-parachain:latest"
  command = "./target/debug/parachain-template-node"
  # This makes this node a full node instead of a collator (despite the schema name)
  validator = false
