[package]
name = "tuxedo-core"
version = "1.0.0-dev"
repository = 'https://github.com/Off-Narrative-Labs/Tuxedo'
edition = "2021"
license = "Apache-2.0"
description = "Core components that all Tuxedo runtimes will use."

[dependencies]
log = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }
parity-scale-codec = { version = '3.4.0', default-features = false, features = ['derive'] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
parity-util-mem = { version = '0.12.0', optional = true }

sp-api = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false}
sp-debug-derive = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false, features = ["force-debug"] }
sp-core = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false}
sp-io = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false, features = ["with-tracing"] }
sp-runtime = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false}
sp-std = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false}
sp-storage = { git = 'https://github.com/paritytech/substrate', tag = "monthly-2023-03", default_features = false}

[dev-dependencies]
array-bytes = "6.0.0"

[features]
default = ["std"]
std = [
	"sp-debug-derive/std",
	"parity-scale-codec/std",
	"sp-core/std",
	"sp-std/std",
	"serde",
	"sp-api/std",
	"sp-io/std",
	"sp-runtime/std",
	"parity-util-mem",
	"sp-storage/std",
]
