name: Check Markdown Links

on: [push]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        # links that are okay (http status returns 200) will not be shown
        use-quiet-mode: 'yes'
        # showing the details on links returning error
        use-verbose-mode: 'yes'
        # Custom config just ignores crates.io links because they are always false positive
        #config-file: '.github/workflows/mlc_config.json'